### ISSUE TITLE
add emzyme in preset

### ISSUE THREAD

**Issue by gasolin** [mozilla-neutrino/neutrino-preset-react#4]
[emzyme](https://github.com/airbnb/enzyme) is a widely used test utility for react, preset-react could include it

**Comment by eliperelman** [comment]
When we created [Neo](https://github.com/mozilla/neo) we included enzyme as it seemed to be popular, but then Jest quickly gained steam again. I think the right thing to do is enable testing to occur through as many frameworks as possible, but bake in none of them. This allows independent upgrades of non-dependent packages, and works well with React, React DOM, and all the testing frameworks. Otherwise this means we would have to re-release the preset with every new version of a dependency that we don't actually use.

Another option is `peerDependency` of `*`, but that seems kinda pointless.
